#!/bin/bash

if [ "$1" = "start" ]; then
    # Run blast-rs and capture output
    output=$(blast-rs start "${@:2}" 2>&1)
    status=$?
    
    if [ $status -eq 0 ]; then
        # Show the environment creation message
        echo "$output" | sed -n '/deactivate ()/q;p'
        # Evaluate the activation script
        eval "$output"
    else
        # If there was an error, show the output
        echo "$output"
        exit $status
    fi
else
    # For all other commands, just pass through to blast-rs
    exec blast-rs "$@"
fi 